services:
  next:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./infra/dockerfiles/frontend.Dockerfile
      args:
        - STAGE=development
        - NEXT_PUBLIC_API_BASE_URL=spring:8080
        - NEXT_PUBLIC_ENV_MODE=DEVELOP_LOCAL

    ports:
      - "3000:3000"

  spring:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./infra/dockerfiles/backend.Dockerfile
      args:
        - STAGE=development
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./infra/env/.env.development.local
    ports:
      - "8080:8080"

  mysql:
    platform: linux/amd64
    image: mysql:8.0
    env_file: ./infra/env/.env.development.local
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always

  nginx:
    platform: linux/amd64
    build:
      context: ./nginx
      dockerfile: ../infra/dockerfiles/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - next
      - spring

volumes:
  shared-data:  # 공유 볼륨 정의