# 개발 환경 + 로컬 환경에서 사용할 도커 컴포즈 파일
# 
services:
  spring:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ../infra/dockerfiles/backend.Dockerfile
    env_file: ./infra/env/.env.production.local
    depends_on:
      mysql:
        condition: service_healthy
    
  next:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: ../infra/dockerfiles/frontend.Dockerfile


  mysql:
    platform: linux/amd64
    image: mysql:8.0
    env_file: ./infra/env/.env.production.local

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 30s
      retries: 10
    restart: always


  nginx:
    platform: linux/amd64
    build:
      context: ./nginx
      dockerfile: ../infra/dockerfiles/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - next
      - spring