# 개발 환경 + 로컬 환경에서 사용할 도커 컴포즈 파일
# 
services:
  spring:
    platform: linux/amd64
    image: wnsgh712/s12p21e107-spring:latest
    env_file: ./infra/env/.env.production
    depends_on:
      mysql:
        condition: service_healthy
    
  next:
    platform: linux/amd64
    image: wnsgh712/s12p21e107-next:latest


  mysql:
    platform: linux/amd64
    image: mysql:8.0
    env_file: ./infra/env/.env.production

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10
    restart: always


  nginx:
    platform: linux/amd64
    image: wnsgh712/s12p21e107-nginx:latest
    ports:
      - "80:80"
    depends_on: 
      - next
      - spring