services:
  spring-generator:
    build:
      context: .
      dockerfile: infra/dockerfiles/generator.Dockerfile
    volumes:
      - ./backend/generated:/backend
    command: 
      - "generate"
      - "-i"
      - "dinggading-api.yaml"
      - "-g"
      - "spring"
      - "-o"
      - "/backend"
      - "-t"
      - "spring-custom-generator/custom-codegen"
      - "-c"
      - "spring-custom-generator/config.json"
    restart: "no"
    
  axios-generator:
    build:
      context: .
      dockerfile: infra/dockerfiles/generator.Dockerfile
    volumes:
      - ./frontend/generated:/frontend
    command: 
      - "generate"
      - "-i"
      - "dinggading-api.yaml"
      - "-g"
      - "typescript-axios"
      - "-o"
      - "/frontend"
      - "-t"
      - "axios-custom-generator/custom-codegen"
      - "-c"
      - "axios-custom-generator/config.json"
    restart: "no"
    