
@memberId = e571b3fd-dcd9-4ccf-abf2-bd3247d5cb0c
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3NUb2tlbiIsInVzZXJuYW1lIjoicWtyd25zZ2g3MXdAZ21haWwuY29tIiwiaWQiOiJlNTcxYjNmZC1kY2Q5LTRjY2YtYWJmMi1iZDMyNDdkNWNiMGMiLCJpYXQiOjE3NDI5NzM4MDcsImV4cCI6MTc0NDY3ODg0MH0.qLF75VTnU0VqITsWzJfcWnSVTg3ccDhOj30T4MlWqgg
@instrument = DRUM

### 랭크 조회
GET {{base_url}}/api/members/{{memberId}}/ranks
Content-Type: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Validate", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### 악기 별 조회
GET http://localhost:8080/api/members/me/ranks/{{instrument}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
#     * GET /api/members/me/ranks : 내 악기별 랭크 정보 조회
#     * 현재 로그인한 회원의 악기별 랭크 정보를 조회합니다.
#     *
#     * @return 회원 악기별 랭크 정보 응답 (status code 200)
#     *         or 인증되지 않은 요청입니다. (status code 401)
GET http://localhost:8080/api/members/me/ranks
Content-Type: application/json
Authorization: Bearer {{token}}