-- Insert into song
INSERT INTO song (created_at, artist, updated_at, song_filename, title, youtube_url, description)
VALUES ('2025-04-07 23:02:45', 'Cranberries', NULL, 'original_Cranberries-Zombie.wav', 'Zombie',
        'bronze_bass_Cranberries-Zombie_ex.wav', NULL),
       ('2025-04-07 23:02:45', 'Day6', NULL, 'original_Day6-HAPPY.wav', 'HAPPY', 'bronze_bass_Day6-HAPPY_ex.wav', NULL),
       ('2025-04-07 23:02:45', '윤도현', NULL, 'original_윤도현-나는 나비.wav', '나는 나비', 'bronze_bass_윤도현-나는 나비_ex.wav', NULL),
       ('2025-04-07 23:02:45', '전기뱀장어', NULL, 'original_전기뱀장어-미로.wav', '미로', 'bronze_bass_전기뱀장어-미로_ex.wav', NULL),
       ('2025-04-07 23:02:45', '카더가든', NULL, 'original_카더가든-꿈을 꿨어요.wav', '꿈을 꿨어요', 'bronze_bass_카더가든-꿈을 꿨어요_ex.wav',
        NULL),
       ('2025-04-07 23:02:45', '백예린', NULL, 'original_백예린-Square.wav', 'Square', 'bronze_guitar_백예린-Square_ex.wav',
        NULL),
       ('2025-04-07 23:02:45', '쏜애플', NULL, 'original_쏜애플-시퍼런 봄.wav', '시퍼런 봄', 'gold_bass_쏜애플-시퍼런 봄_ex.wav', NULL),
       ('2025-04-07 23:02:45', 'QWER', NULL, 'original_QWER-불꽃놀이.wav', '불꽃놀이', 'silver_bass_QWER-불꽃놀이_ex.wav', NULL),
       ('2025-04-07 23:02:45', '카더가든', NULL, 'original_카더가든-가까운 듯 먼 그대여.wav', '가까운 듯 먼 그대여',
        'silver_bass_카더가든-가까운 듯 먼 그대여_ex.wav', NULL);

-- Insert into song_instrument_pack
INSERT INTO song_instrument_pack (created_at, updated_at, pack_name, song_pack_instrument, song_pack_tier)
VALUES ('2025-04-07 23:02:45', NULL, 'BASS_BRONZE', 'BASS', 'BRONZE'),
       ('2025-04-07 23:02:45', NULL, 'GUITAR_BRONZE', 'GUITAR', 'BRONZE'),
       ('2025-04-07 23:02:45', NULL, 'BASS_GOLD', 'BASS', 'GOLD'),
       ('2025-04-07 23:02:45', NULL, 'GUITAR_GOLD', 'GUITAR', 'GOLD'),
       ('2025-04-07 23:02:45', NULL, 'BASS_SILVER', 'BASS', 'SILVER'),
       ('2025-04-07 23:02:45', NULL, 'GUITAR_SILVER', 'GUITAR', 'SILVER');

-- Insert into song_by_instrument
INSERT INTO song_by_instrument (created_at, song_id, song_instrument_pack_id, updated_at,
                                song_by_instrument_analysis_json, song_by_instrument_ex_filename,
                                song_by_instrument_filename, instrument, tier)
VALUES ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'Cranberries' AND title = 'Zombie'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_BRONZE'), NULL,
        'bronze_bass_Cranberries-Zombie.json', 'bronze_bass_Cranberries-Zombie_ex.wav',
        'bronze_bass_Cranberries-Zombie.wav', 'BASS', 'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'Day6' AND title = 'HAPPY'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_BRONZE'), NULL,
        'bronze_bass_Day6-HAPPY.json', 'bronze_bass_Day6-HAPPY_ex.wav', 'bronze_bass_Day6-HAPPY.wav', 'BASS', 'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '윤도현' AND title = '나는 나비'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_BRONZE'), NULL,
        'bronze_bass_윤도현-나는 나비.json', 'bronze_bass_윤도현-나는 나비_ex.wav', 'bronze_bass_윤도현-나는 나비.wav', 'BASS', 'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '전기뱀장어' AND title = '미로'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_BRONZE'), NULL,
        'bronze_bass_전기뱀장어-미로.json', 'bronze_bass_전기뱀장어-미로_ex.wav', 'bronze_bass_전기뱀장어-미로.wav', 'BASS', 'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '카더가든' AND title = '꿈을 꿨어요'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_BRONZE'), NULL,
        'bronze_bass_카더가든-꿈을 꿨어요.json', 'bronze_bass_카더가든-꿈을 꿨어요_ex.wav', 'bronze_bass_카더가든-꿈을 꿨어요.wav', 'BASS',
        'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'Cranberries' AND title = 'Zombie'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_BRONZE'), NULL,
        'bronze_guitar_Cranberries-Zombie.json', 'bronze_guitar_Cranberries-Zombie_ex.wav',
        'bronze_guitar_Cranberries-Zombie.wav', 'GUITAR', 'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '백예린' AND title = 'Square'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_BRONZE'), NULL,
        'bronze_guitar_백예린-Square.json', 'bronze_guitar_백예린-Square_ex.wav', 'bronze_guitar_백예린-Square.wav', 'GUITAR',
        'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '윤도현' AND title = '나는 나비'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_BRONZE'), NULL,
        'bronze_guitar_윤도현-나는 나비.json', 'bronze_guitar_윤도현-나는 나비_ex.wav', 'bronze_guitar_윤도현-나는 나비.wav', 'GUITAR',
        'BRONZE'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '쏜애플' AND title = '시퍼런 봄'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_GOLD'), NULL,
        'gold_bass_쏜애플-시퍼런 봄.json', 'gold_bass_쏜애플-시퍼런 봄_ex.wav', 'gold_bass_쏜애플-시퍼런 봄.wav', 'BASS', 'GOLD'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '쏜애플' AND title = '시퍼런 봄'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_GOLD'), NULL,
        'gold_guitar_쏜애플-시퍼런 봄.json', 'gold_guitar_쏜애플-시퍼런 봄_ex.wav', 'gold_guitar_쏜애플-시퍼런 봄.wav', 'GUITAR', 'GOLD'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'QWER' AND title = '불꽃놀이'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_SILVER'), NULL,
        'silver_bass_QWER-불꽃놀이.json', 'silver_bass_QWER-불꽃놀이_ex.wav', 'silver_bass_QWER-불꽃놀이.wav', 'BASS', 'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '백예린' AND title = 'Square'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_SILVER'), NULL,
        'silver_bass_백예린-Square.json', 'silver_bass_백예린-Square_ex.wav', 'silver_bass_백예린-Square.wav', 'BASS', 'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '카더가든' AND title = '가까운 듯 먼 그대여'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'BASS_SILVER'), NULL,
        'silver_bass_카더가든-가까운 듯 먼 그대여.json', 'silver_bass_카더가든-가까운 듯 먼 그대여_ex.wav', 'silver_bass_카더가든-가까운 듯 먼 그대여.wav',
        'BASS', 'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'Day6' AND title = 'HAPPY'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_SILVER'), NULL,
        'silver_guitar_Day6-HAPPY.json', 'silver_guitar_Day6-HAPPY_ex.wav', 'silver_guitar_Day6-HAPPY.wav', 'GUITAR',
        'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = 'QWER' AND title = '불꽃놀이'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_SILVER'), NULL,
        'silver_guitar_QWER-불꽃놀이.json', 'silver_guitar_QWER-불꽃놀이_ex.wav', 'silver_guitar_QWER-불꽃놀이.wav', 'GUITAR',
        'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '전기뱀장어' AND title = '미로'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_SILVER'), NULL,
        'silver_guitar_전기뱀장어-미로.json', 'silver_guitar_전기뱀장어-미로_ex.wav', 'silver_guitar_전기뱀장어-미로.wav', 'GUITAR',
        'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '카더가든' AND title = '가까운 듯 먼 그대여'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_SILVER'), NULL,
        'silver_guitar_카더가든-가까운 듯 먼 그대여.json', 'silver_guitar_카더가든-가까운 듯 먼 그대여_ex.wav',
        'silver_guitar_카더가든-가까운 듯 먼 그대여.wav', 'GUITAR', 'SILVER'),
       ('2025-04-07 23:02:45', (SELECT song_id FROM song WHERE artist = '카더가든' AND title = '꿈을 꿨어요'),
        (SELECT song_instrument_pack_id FROM song_instrument_pack WHERE pack_name = 'GUITAR_SILVER'), NULL,
        'silver_guitar_카더가든-꿈을 꿨어요.json', 'silver_guitar_카더가든-꿈을 꿨어요_ex.wav', 'silver_guitar_카더가든-꿈을 꿨어요.wav', 'GUITAR',
        'SILVER');
