openapi: 3.0.0
info:
  title: Band API
  description: 밴드 관련 API
  version: 1.0.0
  contact:
    name: 딩가딩
servers:
  - url: http://localhost:8080/api/
    description: Local development server

tags:
  - name: Member
    description: 멤버 관련 API


paths:
  /members/{memberId}/profile:
    get:
      tags:
        - Member
      operationId: getMemberProfile
      summary: 회원 프로필 조회
      description: 회원의 상세 프로필 정보를 조회합니다. 악기별 티어, 선호 밴드 등 포함
      security:
        - BearerAuth: []
      parameters:
        - $ref: './components/parameters/member-id.yaml#/MemberId'
      responses:
        '200':
          description: 회원 프로필 정보 조회 성공
          content:
            application/json:
              schema:
                $ref: './components/schemas/member-profile.yaml#/MemberProfile'

        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: './components/schemas/problem-detail.yaml#/ProblemDetail'

        '404':
          description: 회원을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: './components/schemas/problem-detail.yaml#/ProblemDetail'

        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: './components/schemas/problem-detail.yaml#/ProblemDetail'




components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT 인증 토큰을 사용합니다. 예: Bearer {token}'


