openapi: 3.0.0
info:
  title: 딩가딩 Recruitment API
  version: 1.0.0
  description: "밴드 구인 공고 관련 API 명세서"
  contact:
    email: nykim.ssafy2024@gmail.com

servers:
  - url: https://localhost:8080
    description: 스프링 서버
  - url: https://localhost:8081
    description: 목 서버

tags:
  - name: Recruitment
    description: 밴드 구인 관련 API - 개발 완료

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT 인증 토큰을 사용합니다. 예: Bearer {token}"

  parameters:
    # 경로 파라미터 모음
    BandId:
      name: bandId
      in: path
      description: "밴드 ID"
      required: true
      schema:
        type: integer
        format: int64

    RecruitmentId:
      name: recruitmentId
      in: path
      description: "구인 공고 ID"
      required: true
      schema:
        type: integer
        format: int64

    InstrumentId:
      name: instrumentId
      in: path
      description: "모집 악기 ID"
      required: true
      schema:
        type: integer
        format: int64

    ApplicantId:
      name: applicantId
      in: path
      description: "지원자 ID"
      required: true
      schema:
        type: string
        format: uuid

    RecruitmentStatusParam:
      name: recruitmentStatus
      in: path
      description: "구인 공고 상태"
      required: true
      schema:
        $ref: "#/components/schemas/RecruitmentStatus"

  schemas:
    # 에러 응답 스키마
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

    # 페이지네이션 관련 스키마
    PageableDTO:
      type: object
      properties:
        page:
          type: integer
          description: "현재 페이지 번호"
        size:
          type: integer
          description: "페이지 크기"
        totalElements:
          type: integer
          description: "전체 요소 수"
        totalPages:
          type: integer
          description: "전체 페이지 수"
      required:
        - page
        - size
        - totalElements
        - totalPages

    # 열거형 정의
    Instrument:
      type: string
      enum: [VOCAL, GUITAR, DRUM, BASS]
      description: "악기 유형"

    Tier:
      type: string
      enum: [UNRANKED, IRON, BRONZE, SILVER, GOLD, PLATINUM, DIAMOND]
      description: "티어 레벨"

    RecruitmentStatus:
      type: string
      enum: [READY, RECRUITING, COMPLETED]
      description: "구인 공고 상태"

    # 기본 DTO 스키마
    RecruitmentDTO:
      type: object
      properties:
        bandRecruitmentId:
          type: integer
          format: int64
          description: "구인 공고 ID"
        bandId:
          type: integer
          format: int64
          description: "밴드 ID"
        title:
          type: string
          description: "공고 제목"
        description:
          type: string
          description: "공고 설명"
        auditionDate:
          type: string
          format: date-time
          description: "오디션 날짜 및 시간"
        status:
          $ref: "#/components/schemas/RecruitmentStatus"
        auditionSongId:
          type: integer
          format: int64
          description: "오디션 곡 ID"
        auditionSongTitle:
          type: string
          description: "오디션 곡 제목"
        createdAt:
          type: string
          format: date-time
          description: "생성 일시"
        updatedAt:
          type: string
          format: date-time
          description: "수정 일시"
      required:
        - bandRecruitmentId
        - bandId
        - title
        - auditionDate
        - auditionSongId
        - status

    PageRecruitmentDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/RecruitmentDTO"
        pageable:
          $ref: "#/components/schemas/PageableDTO"
      required:
        - content
        - pageable

    RecruitmentInstrumentDTO:
      type: object
      properties:
        bandRecruitmentInstrumentsId:
          type: integer
          format: int64
          description: "모집 악기 ID"
        bandRecruitmentId:
          type: integer
          format: int64
          description: "구인 공고 ID"
        instrument:
          $ref: "#/components/schemas/Instrument"
        requiredTier:
          $ref: "#/components/schemas/Tier"
        maxSize:
          type: integer
          description: "모집 인원 수"
        currentApplicants:
          type: integer
          description: "현재 지원자 수"
      required:
        - bandRecruitmentInstrumentsId
        - bandRecruitmentId
        - instrument
        - requiredTier
        - maxSize

    ApplicantDTO:
      type: object
      properties:
        bandRecruitmentApplicantId:
          type: integer
          format: int64
          description: "지원자 ID"
        bandRecruitmentInstrumentsId:
          type: integer
          format: int64
          description: "모집 악기 ID"
        applicantId:
          type: string
          format: uuid
          description: "회원 ID"
        nickname:
          type: string
          description: "회원 닉네임"
        profileImgUrl:
          type: string
          description: "회원 프로필 이미지 URL"
        instrument:
          $ref: "#/components/schemas/Instrument"
        tier:
          $ref: "#/components/schemas/Tier"
        applyDate:
          type: string
          format: date-time
          description: "지원 일시"
      required:
        - bandRecruitmentApplicantId
        - bandRecruitmentInstrumentsId
        - applicantId
        - instrument

  # 요청 본문 정의
  requestBodies:
    CreateRecruitmentRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: "공고 제목"
              description:
                type: string
                description: "공고 설명"
              auditionDate:
                type: string
                format: date-time
                description: "오디션 날짜 및 시간"
              auditionSongId:
                type: integer
                format: int64
                description: "오디션 곡 ID"
            required:
              - title
              - auditionDate
              - auditionSongId

    UpdateRecruitmentRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: "공고 제목"
              description:
                type: string
                description: "공고 설명"
              auditionDate:
                type: string
                format: date-time
                description: "오디션 날짜 및 시간"
              auditionSongId:
                type: integer
                format: int64
                description: "오디션 곡 ID"
            required:
              - title
              - auditionDate
              - auditionSongId

    AddRecruitmentInstrumentRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              instrument:
                $ref: "#/components/schemas/Instrument"
              requiredTier:
                $ref: "#/components/schemas/Tier"
              maxSize:
                type: integer
                description: "모집 인원 수"
                default: 1
            required:
              - instrument
              - requiredTier
              - maxSize

    ApplyRecruitmentRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              applicantId:
                type: string
                format: uuid
                description: "지원자 ID"
              bandRecruitmentInstrumentsId:
                type: integer
                format: int64
                description: "지원할 악기 포지션 ID"
            required:
              - applicantId
              - bandRecruitmentInstrumentsId

  # 응답 정의
  responses:
    # 성공 응답
    SuccessNoContent:
      description: "성공적으로 처리되었습니다."
      content: {}

    SuccessAccepted:
      description: "성공적으로 승인되었습니다."

    SuccessRejected:
      description: "성공적으로 거절되었습니다."

    # 비즈니스 응답
    RecruitmentResponse:
      description: "구인 공고 정보"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RecruitmentDTO"

    RecruitmentListResponse:
      description: "구인 공고 목록"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PageRecruitmentDTO"

    RecruitmentInstrumentResponse:
      description: "모집 악기 정보"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RecruitmentInstrumentDTO"

    RecruitmentInstrumentListResponse:
      description: "모집 악기 목록"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/RecruitmentInstrumentDTO"

    ApplicantResponse:
      description: "지원자 정보"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApplicantDTO"

    ApplicantListResponse:
      description: "지원자 목록"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ApplicantDTO"

    # 에러 응답
    NotFoundException:
      description: "요청한 리소스를 찾을 수 없습니다."
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ProblemDetail"
              - type: object
                properties:
                  title:
                    type: string
                    example: "리소스를 찾을 수 없습니다."

    BadRequestException:
      description: "잘못된 요청입니다."
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ProblemDetail"
              - type: object
                properties:
                  title:
                    type: string
                    example: "잘못된 요청입니다."

    UnauthorizedException:
      description: "인증되지 않은 요청입니다."
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ProblemDetail"
              - type: object
                properties:
                  title:
                    type: string
                    example: "인증되지 않은 요청입니다."

    ForbiddenException:
      description: "접근 권한이 없습니다."
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ProblemDetail"
              - type: object
                properties:
                  title:
                    type: string
                    example: "접근 권한이 없습니다."

security:
  - BearerAuth: []

paths:
  /api/bands/recruitments:
    get:
      tags:
        - Recruitment
      operationId: getAllRecruitments
      x-spring-paginated: true
      summary: "전체 구인 공고 목록 조회"
      description: "전체 구인 공고 목록을 조회합니다. 페이징 처리된 결과를 반환합니다."
      responses:
        "200":
          $ref: "#/components/responses/RecruitmentListResponse"

  /api/bands/{bandId}/recruitments:
    get:
      tags:
        - Recruitment
      operationId: getBandRecruitment
      summary: "밴드 구인 공고 조회"
      description: "밴드의 구인 공고를 조회합니다. 밴드는 동시간대에 하나의 구인 공고만 가질 수 있습니다."
      parameters:
        - $ref: "#/components/parameters/BandId"
      responses:
        "200":
          $ref: "#/components/responses/RecruitmentResponse"
        "404":
          $ref: "#/components/responses/NotFoundException"

    post:
      tags:
        - Recruitment
      operationId: createBandRecruitment
      summary: "밴드 구인 공고 등록"
      description: "밴드에 새로운 구인 공고를 등록합니다. 제목, 설명, 오디션 날짜, 오디션 곡 등 포함. 밴드는 동시간대에 하나의 구인 공고만 가질 수 있습니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
      requestBody:
        $ref: "#/components/requestBodies/CreateRecruitmentRequest"
      responses:
        "201":
          $ref: "#/components/responses/RecruitmentResponse"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}:
    patch:
      tags:
        - Recruitment
      operationId: updateBandRecruitment
      summary: "밴드 구인 공고 수정"
      description: "특정 구인 공고 정보를 수정합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
      requestBody:
        $ref: "#/components/requestBodies/UpdateRecruitmentRequest"
      responses:
        "200":
          $ref: "#/components/responses/RecruitmentResponse"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

    delete:
      tags:
        - Recruitment
      operationId: deleteBandRecruitment
      summary: "밴드 구인 공고 삭제"
      description: "특정 구인 공고를 삭제합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
      responses:
        "204":
          $ref: "#/components/responses/SuccessNoContent"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/{recruitmentStatus}:
    post:
      tags:
        - Recruitment
      operationId: updateRecruitmentStatus
      summary: "밴드 구인 공고 상태 변경"
      description: "밴드 구인 프로세스 상태를 변경합니다 (모집 중, 모집 완료)"
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
        - $ref: "#/components/parameters/RecruitmentStatusParam"
      responses:
        "200":
          $ref: "#/components/responses/RecruitmentResponse"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/instruments:
    get:
      tags:
        - Recruitment
      operationId: getRecruitmentInstruments
      summary: "구인 공고 모집 악기 목록 조회"
      description: "구인 공고의 모집 악기 포지션 정보를 조회합니다. 각 포지션별 요구 티어, 모집 인원 포함"
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
      responses:
        "200":
          $ref: "#/components/responses/RecruitmentInstrumentListResponse"
        "404":
          $ref: "#/components/responses/NotFoundException"

    post:
      tags:
        - Recruitment
      operationId: addRecruitmentInstrument
      summary: "구인 공고 악기 포지션 추가"
      description: "구인 공고에 새로운 악기 포지션을 추가합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
      requestBody:
        $ref: "#/components/requestBodies/AddRecruitmentInstrumentRequest"
      responses:
        "201":
          $ref: "#/components/responses/RecruitmentInstrumentResponse"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/instruments/{instrumentId}:
    delete:
      tags:
        - Recruitment
      operationId: removeRecruitmentInstrument
      summary: "구인 공고 악기 포지션 제거"
      description: "구인 공고에서 특정 악기 포지션을 제거합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
        - $ref: "#/components/parameters/InstrumentId"
      responses:
        "204":
          $ref: "#/components/responses/SuccessNoContent"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/applicants:
    get:
      tags:
        - Recruitment
      operationId: getRecruitmentApplicants
      summary: "구인 공고 지원자 목록 조회"
      description: "구인 공고에 지원한 지원자 목록을 조회합니다."
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
      responses:
        "200":
          $ref: "#/components/responses/ApplicantListResponse"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /recruitments/{recruitmentId}/apply:
    post:
      tags:
        - Recruitment
      operationId: applyRecruitment
      summary: "구인 공고 지원"
      description: "구인 공고에 지원합니다. 지원자 ID, 악기 포지션 포함"
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/RecruitmentId"
      requestBody:
        $ref: "#/components/requestBodies/ApplyRecruitmentRequest"
      responses:
        "201":
          $ref: "#/components/responses/ApplicantResponse"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /recruitments/{recruitmentId}/applicants/{applicantId}:
    delete:
      tags:
        - Recruitment
      operationId: cancelRecruitmentApplication
      summary: "구인 공고 지원 취소"
      description: "구인 공고 지원을 취소합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/RecruitmentId"
        - $ref: "#/components/parameters/ApplicantId"
      responses:
        "204":
          $ref: "#/components/responses/SuccessNoContent"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/accept/{applicantId}:
    post:
      tags:
        - Recruitment
      operationId: acceptApplicant
      summary: "지원자 승인"
      description: "특정 지원자의 밴드 가입을 승인합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
        - $ref: "#/components/parameters/ApplicantId"
      responses:
        "200":
          $ref: "#/components/responses/SuccessAccepted"
        "400":
          $ref: "#/components/responses/BadRequestException"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"

  /api/bands/{bandId}/recruitments/{recruitmentId}/reject/{applicantId}:
    post:
      tags:
        - Recruitment
      operationId: rejectApplicant
      summary: "지원자 거절"
      description: "특정 지원자의 밴드 가입을 거절합니다."
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/BandId"
        - $ref: "#/components/parameters/RecruitmentId"
        - $ref: "#/components/parameters/ApplicantId"
      responses:
        "200":
          $ref: "#/components/responses/SuccessRejected"
        "403":
          $ref: "#/components/responses/ForbiddenException"
        "404":
          $ref: "#/components/responses/NotFoundException"
